### PR TITLE
refactor(toggle): prevent clickable area expanding past toggle-slider

### PR DESCRIPTION
**Pull request by gavin-everett-genesys**
prevent clickable area expanding past toggle-slider

[COMUI-2486](https://inindca.atlassian.net/browse/COMUI-2486)

[COMUI-2486]: https://inindca.atlassian.net/browse/COMUI-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gavin-everett-genesys** [comment]
Need to update tests.

**Review by jordanstith15 — APPROVED** [review]

**Comment by jason-evans-genesys** [comment]
@gavin-everett-genesys The clickable area issue is fixed. I did notice a new bug with gux-toggle where navigating to a toggle component with the tab key and then pressing enter does not change the toggle state. Do you know if this is expected behavior? If it's a bug I can create a new ticket for it, but was just wondering first.

**Comment by gavin-everett-genesys** [comment]
> @gavin-everett-genesys The clickable area issue is fixed. I did notice a new bug with gux-toggle where navigating to a toggle component with the tab key and then pressing enter does not change the toggle state. Do you know if this is expected behavior? If it's a bug I can create a new ticket for it, but was just wondering first.

For the `toggle` component the space key can be used to switch state 

https://spark.genesys.com/latest/components/forms-and-inputs/toggle/accessibility-MiPA1h4X

**Review by jason-evans-genesys — APPROVED** [review]

**Comment by jason-evans-genesys** [comment]
> > @gavin-everett-genesys The clickable area issue is fixed. I did notice a new bug with gux-toggle where navigating to a toggle component with the tab key and then pressing enter does not change the toggle state. Do you know if this is expected behavior? If it's a bug I can create a new ticket for it, but was just wondering first.
> 
> For the `toggle` component the space key can be used to switch state
> 
> https://spark.genesys.com/latest/components/forms-and-inputs/toggle/accessibility-MiPA1h4X

Thanks for the info. It doesn't look like the space bar is changing the toggle state. I can log a bug for this to put in the backlog.

**Comment by gavin-everett-genesys** [comment]
> > > @gavin-everett-genesys The clickable area issue is fixed. I did notice a new bug with gux-toggle where navigating to a toggle component with the tab key and then pressing enter does not change the toggle state. Do you know if this is expected behavior? If it's a bug I can create a new ticket for it, but was just wondering first.
> > 
> > 
> > For the `toggle` component the space key can be used to switch state
> > https://spark.genesys.com/latest/components/forms-and-inputs/toggle/accessibility-MiPA1h4X
> 
> Thanks for the info. It doesn't look like the space bar is changing the toggle state. I can log a bug for this to put in the backlog. https://inindca.atlassian.net/browse/COMUI-2505

Good spot 👍  , I have fixed the toggle state issue in this PR as it was a minor change. I also removed the `Enter` case for the key presses as it should not be included.

**Review by jason-evans-genesys — APPROVED** [review]

**Pull request merged**
