### PR TITLE
feat(form-fields): Update the spacing on form fields

### PR DESCRIPTION
**Pull request by 321gillian**
Changing 8px to 4px above and below the inputs

### CODE REVIEW

**Comment by gavin-everett-genesys** [comment]
I am not sure if this is working correctly as I still see the `8px` gaps in the following, `form-field-color` `form-field-number` `form-field-phone`

**Comment by 321gillian** [comment]
> https://apps.inindca.com/common-ui-docs/genesys-webcomponents/feature/COMUI-3033-gap

Screenshot 2024-08-22 at 12 26 29
Just to confirm, this is the gap I'm referencing here. Is that the same one you're seeing as 8px?

**Comment by gavin-everett-genesys** [comment]
> > https://apps.inindca.com/common-ui-docs/genesys-webcomponents/feature/COMUI-3033-gap
> 
> Screenshot 2024-08-22 at 12 26 29 Just to confirm, this is the gap I'm referencing here. Is that the same one you're seeing as 8px?

Yeah, its weird its working now maybe I viewed the branch too early not sure :D

**Review by daragh-king-genesys — APPROVED** [review]

**Comment by gavin-everett-genesys** [comment]
I know this is not specified in the ticket but should the label-position of beside be updated aswell as they are currently 8px.

**Comment by 321gillian** [comment]
> I know this is not specified in the ticket but should the label-position of beside be updated aswell as they are currently 8px.

I'll check

**Comment by 321gillian** [comment]
> I know this is not specified in the ticket but should the label-position of beside be updated aswell as they are currently 8px.

I'll check this with UX. Sorry I closed this by accident, reopened now

**Comment by 321gillian** [comment]
> I know this is not specified in the ticket but should the label-position of beside be updated aswell as they are currently 8px.

8px beside is still correct, confirmed

**Pull request merged**
