### PR TITLE
(blank-state) - tokens removed/updated

### PR DESCRIPTION
**Pull request by gavin-everett-genesys**
I was just wondering when I run `new-tokens-data` should the old files be updating as-well for example the tokens will still exist in `_gse-ui-feedback.scss` or is it okay for those files to go out of sync.

### CODE REVIEW

**Comment by 321gillian** [comment]
> I was just wondering when I run `new-tokens-data` should the old files be updating as-well for example the tokens will still exist in `_gse-ui-feedback.scss` or is it okay for those files to go out of sync.

I think on the UX side they need to update the `data-old/tokens.json` file as well as the new stuff. Had a similar thing in the form field gap changes lately

**Comment by VirtualClover** [comment]
cc. @MonseGarciaLimon

**Comment by daragh-king-genesys** [comment]
@gavin-everett-genesys can you rebase this on main

**Comment by gavin-everett-genesys** [comment]
I have resolved the conflicts on this PR now I had one question should we also be updating the `data-old/tokens.json` file also to remove the tokens from there ?

**Comment by 321gillian** [comment]
Screenshot 2024-10-29 at 11 26 09
Does this one need to go too?

**Review by 321gillian — APPROVED** [review]

**Pull request merged**
