### PR TITLE
feat(button-slot): allow the slotting of links in gux-button-slot

### PR DESCRIPTION
**Pull request by 321gillian**
COMUI-2746

### CODE REVIEW

**Comment by katie-bobbe-genesys** [comment]
Semantically, a button is different from a link. I'm almost thinking it might make more sense to create a new component, `gux-anchor-button` that just slots an anchor and provides the style of the button. This way so that consumers are not using anchors and buttons interchangeably. What do you think?

**Comment by thomas-c-dillon** [comment]
> Semantically, a button is different from a link. I'm almost thinking it might make more sense to create a new component, `gux-anchor-button` that just slots an anchor and provides the style of the button. This way so that consumers are not using anchors and buttons interchangeably. What do you think?

I agree with this if UX wants this change to go forward. I still caution against any links that look like buttons at all.

**Comment by 321gillian** [comment]
I've started a conversation with the UX team about how to approach these. Will revert when I have more.

**Comment by 321gillian** [comment]
Closing this as it needs further consideration before going anywhere else

**Pull request closed without merging**
