### PR TITLE
Datepicker tokens added

### PR DESCRIPTION
**Pull request by jason-evans-genesys**
Ticket this references: https://inindca.atlassian.net/browse/COMUI-2771

This was a branch that UX had created so we could get new tokens for the datepicker component.

### CODE REVIEW

**Comment by katie-bobbe-genesys** [comment]
I think you will need to run `npm run new-tokens-data` on this before merging

**Review by daragh-king-genesys — COMMENTED** [review]
you have to run `npm run new-tokens-data` on this branch to update the token snapshots

**Comment by jason-evans-genesys** [comment]
> npm run new-tokens-data

Good catch. I ran this command in the root folder of the spark repo and it triggered 5k+ file changes. Is this expected? I would've expected less file changes. Looks like all the file changes are in the `dist` folder of the repo. I won't push these file changes until I confirm this is expected.

**Comment by katie-bobbe-genesys** [comment]
> > npm run new-tokens-data
> 
> Good catch. I ran this command in the root folder of the spark repo and it triggered 5k+ file changes. Is this expected? I would've expected less file changes. Looks like all the file changes are in the `dist` folder of the repo. I won't push these file changes until I confirm this is expected.

No we would not expect to push this many changes. You should be seeing about 3 or 4 files change. Do you have a `.gitignore` file in the root of your repo? I can help you look at this issue tomorrow if you want

**Pull request closed without merging**
