### PR TITLE
feat(icons): adding requested icons

### PR DESCRIPTION
**Pull request by conor-darcy**

### CODE REVIEW

**Comment by daragh-king-genesys** [comment]
I would have expected changes to `gux-icon.types.ts` and `generateFontAwesomeIcons.js`like the v4 PR.

**Review by daragh-king-genesys — COMMENTED** [review]
I would have expected changes to gux-icon.types.ts and generateFontAwesomeIcons.jslike the v4 PR.

**Comment by conor-darcy** [comment]
> I would have expected changes to gux-icon.types.ts and generateFontAwesomeIcons.jslike the v4 PR.

Yeah, not sure why generateFontAwesomeIcons.js wont push for me.

**Comment by conor-darcy** [comment]
@daragh-king-genesys Sorted now.

**Review by daragh-king-genesys — APPROVED** [review]

**Pull request merged**
