### PR TITLE
chore: update @types/new-relic-browser dependency

### PR DESCRIPTION
**Pull request by MattCheely**
This was flagged to do in a ticket. Only needed some minor adjustments.

COMUI-1257

### CODE REVIEW

**Comment by MattCheely** [comment]
🤦 Of course everything builds fine, but fails with Jest.

**Comment by jordanstith15** [comment]
> 🤦 Of course everything builds fine, but fails with Jest.

Is the stuff with the CI failure still being worked on?

**Comment by MattCheely** [comment]
> > 🤦 Of course everything builds fine, but fails with Jest.
> 
> Is the stuff with the CI failure still being worked on?

This fell off my radar over the holiday. It was intended to be a quick fix. I'll circle back to it tomorrow morning.

**Review by jason-evans-genesys — APPROVED** [review]

**Review by jason-evans-genesys — CHANGES_REQUESTED** [review]
Looks good, just seeing some failing tests, but other than that all good to go.

**Comment by MattCheely** [comment]
I've hit a whole new set of issues trying to come back to fix the problem with stubbing newrelic in Jest, and it's just not worth the effort for a type upgrade that wasn't causing any problems in the first place.

**Pull request closed without merging**
